development:
  adapter: postgresql
  database: CHANGEME_development
  host: localhost
  encoding: utf8

test: &TEST
  adapter: postgresql
  database: CHANGEME_test
  host: localhost
  encoding: utf8
  min_messages: warning

cucumber:
  <<: *TEST

staging:
  adapter: postgresql
  database: CHANGEME_development

production:
  adapter: postgresql
  database: CHANGEME_development
